# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy application source
COPY . .

# Ensure index.js is executable
RUN chmod +x index.js

# Set the entrypoint
ENTRYPOINT ["node", "index.js"]
